# from the Three Dog Night song: "joy to the world (Jeremiah was a bullfrog)"
puts "joy to the world"
puts "all the boys and girls"
# puts "joy to the fishes in the deep blue sea"
puts "joy to you and me"
